# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postTiya
      POSTGRES_DB: customer_churn
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - churn_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - churn_network


  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postTiya@db:5432/customer_churn
    networks:
      - churn_network
  
volumes:
  pgdata:

networks:
  churn_network:
    driver: bridge